version: 2

executors:
  e2e-executor:
    docker:
      - image: cypress/browsers:node10.16.0-chrome76

jobs:
  e2e:
    executor: e2e-executor
    steps:
      steps:
        - checkout
        - run:
            name: Copy base .env file
            command: cp sample.env .env
        - run:
            name: Install node modules
            command: npm ci
        - run:
            name: End 2 end test command
            command: npm run e2e:ci

workflows:
  version: 2
  tests:
    jobs:
      - e2e:
          filters:
            branches:
              ignore:
                - master