name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.5.5
# ports may not be necessary, try without
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up environment
        run: cp sample.env .env

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run develop
          wait-on: http://localhost:8000
          config: baseUrl=http://localhost:8000
